[project]
dependencies = []
name = "Transformed-Eulerian-Mean"
requires-python = ">= 3.14"
version = "1.0.0"
license = { text = "MIT" }

[tool.hatch.build.targets.wheel]
packages = ["src/tem_pkg"]

[project.scripts]
# Command-name = "package_folder.file_name:function_name"
residual = "tem_pkg.cli:run_residual"
transport-theta = "tem_pkg.cli:run_tracer_transport_theta"
transport-press = "tem_pkg.cli:run_tracer_transport_press"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
[tool.pixi.pypi-dependencies]
transformed_eulerian_mean = { path = ".", editable = true }

[tool.ruff]
# Set the maximum line length
line-length = 200
target-version = "py314"

[tool.ruff.lint]
# Enable specific rules
# E: pycodestyle, F: Pyflakes, I: isort
select = ["E", "F", "I"]
ignore = []

[tool.ruff.format]
# Use double quotes
quote-style = "double"


[tool.pixi.tasks]
# Check for errors without changing files
lint = "ruff check src"
# Automatically fix errors and sort imports
lint-fix = "ruff check src --fix"
# Reformat the code style (spacing, quotes, etc.)
format = "ruff format src"
# Run tests with coverage report
coverage = "pytest tests/ --cov=src/tem_pkg --cov-report=term-missing"

[tool.pixi.dependencies]
xarray = ">=2025.12.0,<2026"
numpy = ">=2.3.5,<3"
scipy = ">=1.16.3,<2"
metpy = ">=1.7.1,<2"
ipython = ">=9.8.0,<10"
ipykernel = ">=7.1.0,<8"
pip = ">=25.3,<26"
toml = ">=0.10.2,<0.11"
h5netcdf = ">=1.7.3,<2"
ruff = ">=0.14.11,<0.15"
pytest = ">=9.0.3,<10"
pytest-cov = ">=7.1.0,<8"
