"""
Integration tests using small synthetic .nc files that mirror the structure of the real
ERA5 and CLAMS input data.  The files live in tests/data/ and are generated by
tests/create_sample_files.py.

Sample file dimensions:
  ERA5  (3 files, 00/06/12 UTC):  30 hybrid × 57 lat × 108 lon
  CLAMS theta (3 files, Jan 1-3): 24 theta   × 30 lat × 36 lon
  CLAMS press (3 files, Jan 1-3): 24 press   × 30 lat × 36 lon

Tests that compare against the large real reference files are kept but
auto-skipped when those files are absent.
"""

import numpy as np
import pytest
import xarray as xr
from pathlib import Path

from transformed_eulerian_mean.utils import binData, addRatioUnits
from transformed_eulerian_mean.file_io import readAndTransposeData, readDataAndGetWeightedAverage
from transformed_eulerian_mean.interpolation import (
    interpolateToThetaAndCombineData,
    interpolateToPressureAndCombineData,
    interpolateToLogPressure,
)
from transformed_eulerian_mean.tracer_transport_theta import tracerTransport as tracerTransportTheta
from transformed_eulerian_mean.tracer_transport_press import tracerTransport as tracerTransportPress
from transformed_eulerian_mean.residual_circulation import TEMCalcs

addRatioUnits()

# ---------------------------------------------------------------------------
# Sample file paths (always present — committed to the repo)
# ---------------------------------------------------------------------------
_SAMPLE_ROOT   = Path(__file__).parent / "data" / "sample_input"
_ERA5_DIR      = _SAMPLE_ROOT / "ERA5"
_CLAMS_TH_DIR  = _SAMPLE_ROOT / "CLaMS_Theta"
_CLAMS_PR_DIR  = _SAMPLE_ROOT / "CLaMS_Press"

# 12 ERA5 snapshots: 00/06/12/18 UTC × Jan 1/2/3
ERA5_FILES = [
    _ERA5_DIR / "era5_sample_00010100.nc",
    _ERA5_DIR / "era5_sample_00010106.nc",
    _ERA5_DIR / "era5_sample_00010112.nc",
    _ERA5_DIR / "era5_sample_00010118.nc",
    _ERA5_DIR / "era5_sample_00010200.nc",
    _ERA5_DIR / "era5_sample_00010206.nc",
    _ERA5_DIR / "era5_sample_00010212.nc",
    _ERA5_DIR / "era5_sample_00010218.nc",
    _ERA5_DIR / "era5_sample_00010300.nc",
    _ERA5_DIR / "era5_sample_00010306.nc",
    _ERA5_DIR / "era5_sample_00010312.nc",
    _ERA5_DIR / "era5_sample_00010318.nc",
]

# 3 CLAMS theta snapshots: Jan 1, 2, 3
CLAMS_THETA_FILES = [
    _CLAMS_TH_DIR / "clams_theta_sample_00010112.nc",
    _CLAMS_TH_DIR / "clams_theta_sample_00010212.nc",
    _CLAMS_TH_DIR / "clams_theta_sample_00010312.nc",
]

# 3 CLAMS pressure snapshots: Jan 1, 2, 3
CLAMS_PRESS_FILES = [
    _CLAMS_PR_DIR / "clams_press_sample_00010112.nc",
    _CLAMS_PR_DIR / "clams_press_sample_00010212.nc",
    _CLAMS_PR_DIR / "clams_press_sample_00010312.nc",
]

# Sample file expected dimensions
ERA5_SIZES  = {"hybrid": 30, "lat": 57, "lon": 108}
CLAMS_SIZES = {"lat": 30, "lon": 36}
NTHETA = 24
NPRESS = 24

# ---------------------------------------------------------------------------
# Target level arrays
# ---------------------------------------------------------------------------
_TARGET_THETA = [300, 350, 400, 450, 500, 600, 700, 800, 900, 1000, 1250, 1500]

_TARGET_LP = [0.0, 2.0, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 35.0, 40.0, 45.0, 50.0]

_TARGET_LP_FULL = [
    0.0, 0.38, 0.74, 1.14, 1.53, 2.0, 2.56, 2.99, 3.45, 4.21, 4.75, 5.58, 6.43,
    7.31, 8.51, 8.82, 9.44, 10.07, 10.71, 11.36, 12.02, 12.69, 13.38, 14.07,
    14.78, 15.14, 15.5, 15.86, 16.23, 16.6, 16.97, 17.35, 17.73, 18.11, 18.5,
    18.9, 19.31, 19.72, 20.14, 20.58, 21.03, 21.49, 21.96, 22.44, 22.94, 23.44,
    23.97, 24.5, 25.06, 25.62, 26.21, 26.81, 27.43, 28.07, 28.73, 29.41, 30.11,
    30.84, 31.59, 32.36, 33.17, 34.0, 34.87, 35.77, 36.7, 37.67, 38.68, 39.73,
    40.83, 41.98, 43.17, 44.42, 45.74, 47.11, 48.56, 50.07, 51.67, 53.36,
    55.14, 57.02, 59.02, 61.13, 63.39, 65.79, 68.35, 71.1, 74.04, 80.59,
]
_TARGET_THETA_FULL = [
    280, 290, 300, 310, 320, 330, 340, 350, 360, 370,
    380, 390, 400, 410, 420, 430, 450, 475, 500, 550,
    600, 650, 700, 800, 900, 1000, 1250, 1500, 2000, 2250, 2600,
]

# ---------------------------------------------------------------------------
# Config factories
# ---------------------------------------------------------------------------

def _theta_config(target_levels=None, **overrides):
    cfg = {
        "verticalDimensionType": "other",
        "thetaName": "THETA",
        "pressureName": "PRESS",
        "meridionalWindName": "V",
        "verticalWindName": "THETA_DOT_TOT",
        "tracerNames": ["BA"],
        "sinksSources": ["0"],
        "massSF": True,
        "FourierTransform": False,
        "Waves": ["1"],
        "binningLat": 2,
        "binningLon": 1,
        "vertDim": "hybrid",
        "latDim": "lat",
        "lonDim": "lon",
        "tracerVertDim": "theta",
        "tracerLatDim": "lat",
        "tracerLonDim": "lon",
        "tracerVerticalDimensionType": "theta",
        "tracerThetaName": "theta",
        "targetLevels": target_levels if target_levels is not None else _TARGET_THETA,
    }
    cfg.update(overrides)
    return cfg


def _press_config(target_levels=None, **overrides):
    cfg = {
        "verticalDimensionType": "other",
        "temperatureName": "THETA",
        "temperatureType": "theta",
        "pressureName": "PRESS",
        "meridionalWindName": "V",
        "verticalWindName": "OMEGA",
        "verticalWindType": "omega",
        "tracerNames": ["BA"],
        "sinksSources": ["0"],
        "massSF": True,
        "FourierTransform": False,
        "Waves": ["1"],
        "binningLat": 2,
        "binningLon": 1,
        "vertDim": "hybrid",
        "latDim": "lat",
        "lonDim": "lon",
        "tracerVertDim": "press",
        "tracerLatDim": "lat",
        "tracerLonDim": "lon",
        "tracerVerticalDimensionType": "pressure",
        "tracerPressureName": "",
        "targetLevels": target_levels if target_levels is not None else _TARGET_LP,
    }
    cfg.update(overrides)
    return cfg


def _tem_config(target_levels=None, **overrides):
    cfg = {
        "zonalWindName": "U",
        "meridionalWindName": "V",
        "temperatureName": "THETA",
        "temperatureType": "theta",
        "verticalWindName": "OMEGA",
        "verticalWindType": "omega",
        "pressureName": "PRESS",
        "verticalDimensionType": "other",
        "saveEddyTerms": False,
        "FourierTransform": False,
        "Waves": ["1"],
        "inputDataDescription": "sample",
        "vertDim": "hybrid",
        "latDim": "lat",
        "lonDim": "lon",
        "targetLevels": target_levels if target_levels is not None else _TARGET_LP,
    }
    cfg.update(overrides)
    return cfg


# ---------------------------------------------------------------------------
# Helper: weighted average of the 3 ERA5 sample files
# ---------------------------------------------------------------------------
def _met_average(req_vars):
    n = len(ERA5_FILES)
    return readDataAndGetWeightedAverage(
        [str(f) for f in ERA5_FILES],
        [1 / n] * n,
        req_vars,
        "hybrid", "lat", "lon",
    )


# ---------------------------------------------------------------------------
# Module-scoped fixtures — run each pipeline once
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def theta_result():
    cfg = _theta_config()
    req = ["THETA", "PRESS", "V", "THETA_DOT_TOT"]
    tracer = readAndTransposeData(str(CLAMS_THETA_FILES[0]), ["BA"], "theta", "lat", "lon")
    met    = _met_average(req)
    interp = interpolateToThetaAndCombineData(tracer, met, req, cfg)
    binned = binData(interp, cfg["binningLat"], cfg["binningLon"])
    result, lats, tlevs = tracerTransportTheta(binned, cfg)
    return result, lats, tlevs, binned


@pytest.fixture(scope="module")
def press_result():
    cfg = _press_config()
    req = ["PRESS", "THETA", "V", "OMEGA"]
    tracer = readAndTransposeData(str(CLAMS_PRESS_FILES[0]), ["BA"], "press", "lat", "lon")
    met    = _met_average(req)
    interp = interpolateToPressureAndCombineData(tracer, met, req, cfg)
    binned = binData(interp, cfg["binningLat"], cfg["binningLon"])
    result, lats, alts = tracerTransportPress(binned, cfg)
    return result, lats, alts, binned


@pytest.fixture(scope="module")
def tem_result():
    import pandas as pd
    cfg = _tem_config()
    req = ["PRESS", "THETA", "U", "V", "OMEGA"]
    ds   = readAndTransposeData(str(ERA5_FILES[2]), req, "hybrid", "lat", "lon")
    ds_lp = interpolateToLogPressure(
        ds, req, "other", cfg["targetLevels"], "hybrid", "lat", "lon", "PRESS"
    )
    return TEMCalcs(cfg, ds_lp, pd.Timestamp("2000-01-01T12"))

# ===========================================================================
# readAndTransposeData / readDataAndGetWeightedAverage
# ===========================================================================

def test_read_era5_sample_shape_and_dims():
    req = ["THETA", "U", "V", "OMEGA", "PRESS"]
    ds = readAndTransposeData(str(ERA5_FILES[0]), req, "hybrid", "lat", "lon")
    assert set(ds.dims) == {"hybrid", "lat", "lon"}
    assert ds.sizes["hybrid"] == ERA5_SIZES["hybrid"]
    assert ds.sizes["lat"]    == ERA5_SIZES["lat"]
    assert ds.sizes["lon"]    == ERA5_SIZES["lon"]
    for v in req:
        assert v in ds


def test_read_era5_all_files_same_shape():
    req = ["THETA"]
    shapes = []
    for f in ERA5_FILES:
        ds = readAndTransposeData(str(f), req, "hybrid", "lat", "lon")
        shapes.append(tuple(ds.sizes[d] for d in ["hybrid", "lat", "lon"]))
    assert len(set(shapes)) == 1, "ERA5 sample files have inconsistent shapes"


def test_read_era5_dim_order():
    ds = readAndTransposeData(str(ERA5_FILES[0]), ["THETA"], "hybrid", "lat", "lon")
    assert list(ds["THETA"].dims) == ["hybrid", "lat", "lon"]


def test_read_clams_theta_all_three_files():
    for f in CLAMS_THETA_FILES:
        ds = readAndTransposeData(str(f), ["BA"], "theta", "lat", "lon")
        assert ds.sizes["theta"] == NTHETA
        assert ds.sizes["lat"]   == CLAMS_SIZES["lat"]
        assert ds.sizes["lon"]   == CLAMS_SIZES["lon"]


def test_read_clams_press_all_three_files():
    for f in CLAMS_PRESS_FILES:
        ds = readAndTransposeData(str(f), ["BA"], "press", "lat", "lon")
        assert ds.sizes["press"] == NPRESS
        assert ds.sizes["lat"]   == CLAMS_SIZES["lat"]
        assert ds.sizes["lon"]   == CLAMS_SIZES["lon"]


def test_weighted_average_single_file_is_identity():
    req = ["V"]
    ds_direct   = readAndTransposeData(str(ERA5_FILES[0]), req, "hybrid", "lat", "lon")
    ds_weighted = readDataAndGetWeightedAverage(
        [str(ERA5_FILES[0])], [1.0], req, "hybrid", "lat", "lon"
    )
    np.testing.assert_array_equal(np.array(ds_direct["V"]), np.array(ds_weighted["V"]))


def test_weighted_average_three_identical_files():
    """Average of three copies with equal weights must equal the original."""
    req = ["V"]
    ds_direct   = readAndTransposeData(str(ERA5_FILES[0]), req, "hybrid", "lat", "lon")
    ds_weighted = readDataAndGetWeightedAverage(
        [str(ERA5_FILES[0])] * 3, [1/3, 1/3, 1/3], req, "hybrid", "lat", "lon"
    )
    np.testing.assert_allclose(np.array(ds_direct["V"]), np.array(ds_weighted["V"]), rtol=1e-5)


def test_weighted_average_all_era5_files_shape():
    req = ["V", "THETA"]
    n = len(ERA5_FILES)
    ds = readDataAndGetWeightedAverage(
        [str(f) for f in ERA5_FILES], [1/n] * n, req, "hybrid", "lat", "lon"
    )
    assert ds.sizes["hybrid"] == ERA5_SIZES["hybrid"]
    assert ds.sizes["lat"]    == ERA5_SIZES["lat"]
    assert ds.sizes["lon"]    == ERA5_SIZES["lon"]


# ===========================================================================
# Theta transport pipeline — interpolation and binning
# ===========================================================================

def test_interpolate_to_theta_output_levels():
    cfg = _theta_config()
    req = ["THETA", "PRESS", "V", "THETA_DOT_TOT"]
    tracer = readAndTransposeData(str(CLAMS_THETA_FILES[0]), ["BA"], "theta", "lat", "lon")
    met    = _met_average(req)
    interp = interpolateToThetaAndCombineData(tracer, met, req, cfg)
    # tracerVerticalDimensionType='theta' means the CLAMS native levels pass through unchanged
    assert interp.sizes["theta"] == NTHETA
    assert interp.sizes["lat"]   == CLAMS_SIZES["lat"]
    assert interp.sizes["lon"]   == CLAMS_SIZES["lon"]


def test_bin_theta_reduces_lat():
    cfg = _theta_config()
    req = ["THETA", "PRESS", "V", "THETA_DOT_TOT"]
    tracer = readAndTransposeData(str(CLAMS_THETA_FILES[0]), ["BA"], "theta", "lat", "lon")
    met    = _met_average(req)
    interp = interpolateToThetaAndCombineData(tracer, met, req, cfg)
    binned = binData(interp, 2, 1)
    assert binned.sizes["lat"] == interp.sizes["lat"] // 2
    assert binned.sizes["lon"] == interp.sizes["lon"]


def test_theta_results_consistent_across_tracer_files(theta_result):
    """Running with the second CLAMS file must produce output with the same shape."""
    cfg = _theta_config()
    req = ["THETA", "PRESS", "V", "THETA_DOT_TOT"]
    tracer2 = readAndTransposeData(str(CLAMS_THETA_FILES[1]), ["BA"], "theta", "lat", "lon")
    met     = _met_average(req)
    interp2 = interpolateToThetaAndCombineData(tracer2, met, req, cfg)
    binned2 = binData(interp2, 2, 1)
    res2, *_ = tracerTransportTheta(binned2, cfg)
    result, *_ = theta_result
    assert result["BA_chi_bar"][0].shape == res2["BA_chi_bar"][0].shape


# ===========================================================================
# Theta transport output variables
# ===========================================================================

def test_theta_output_vars_present(theta_result):
    result, *_ = theta_result
    for var in [
        "PRESS", "massSF",
        "BA_chi_bar", "BA_dt_sum",
        "BA_divm_theta", "BA_divm_lat",
        "BA_m_theta", "BA_m_lat",
        "BA_adv_theta", "BA_adv_lat",
    ]:
        assert var in result, f"Missing: {var}"


def test_theta_chi_bar_shape(theta_result):
    result, lats, tlevs, binned = theta_result
    vals = result["BA_chi_bar"][0]
    vals = vals.magnitude if hasattr(vals, "magnitude") else np.array(vals)
    assert vals.shape == (NTHETA, binned.sizes["lat"])


def test_theta_chi_bar_all_finite(theta_result):
    result, *_ = theta_result
    vals = result["BA_chi_bar"][0]
    vals = vals.magnitude if hasattr(vals, "magnitude") else np.array(vals)
    interior = vals[1:-1, 1:-1]
    assert np.all(np.isfinite(interior)), "chi_bar interior has non-finite values"


def test_theta_chi_bar_positive(theta_result):
    result, *_ = theta_result
    vals = result["BA_chi_bar"][0]
    vals = vals.magnitude if hasattr(vals, "magnitude") else np.array(vals)
    assert np.all(vals[np.isfinite(vals)] >= 0), "age-of-air chi_bar must be non-negative"


def test_theta_massSF_top_zero(theta_result):
    result, *_ = theta_result
    top = result["massSF"][0][-1, :]
    top = top.magnitude if hasattr(top, "magnitude") else np.array(top)
    np.testing.assert_allclose(top, 0.0, atol=1e-4)


def test_theta_dt_sum_identity(theta_result):
    """dt_sum = divm_theta + divm_lat + adv_theta + adv_lat  (sinksSources='0')."""
    result, *_ = theta_result
    def v(k):
        x = result[k][0]
        return x.magnitude if hasattr(x, "magnitude") else np.array(x)
    expected = v("BA_divm_theta") + v("BA_divm_lat") + v("BA_adv_theta") + v("BA_adv_lat")
    dt = v("BA_dt_sum")
    mask = np.isfinite(dt) & np.isfinite(expected)
    np.testing.assert_allclose(dt[mask], expected[mask], rtol=1e-4)


def test_theta_massSF_nonzero(theta_result):
    result, lats, *_ = theta_result
    msf = result["massSF"][0]
    vals = msf.magnitude if hasattr(msf, "magnitude") else np.array(msf)
    assert np.nanmax(np.abs(vals)) > 0, "massSF should be non-zero"


# ===========================================================================
# Press transport output variables
# ===========================================================================

def test_press_output_vars_present(press_result):
    result, *_ = press_result
    for var in [
        "massSF",
        "BA_chi_bar", "BA_dt_sum",
        "BA_divm_z", "BA_divm_lat",
        "BA_m_z", "BA_m_lat",
        "BA_adv_z", "BA_adv_lat",
    ]:
        assert var in result, f"Missing: {var}"


def test_press_chi_bar_all_finite(press_result):
    result, *_ = press_result
    vals = result["BA_chi_bar"][0]
    vals = vals.magnitude if hasattr(vals, "magnitude") else np.array(vals)
    interior = vals[1:-1, 1:-1]
    assert np.all(np.isfinite(interior))


def test_press_chi_bar_positive(press_result):
    result, *_ = press_result
    vals = result["BA_chi_bar"][0]
    vals = vals.magnitude if hasattr(vals, "magnitude") else np.array(vals)
    assert np.all(vals[np.isfinite(vals)] >= 0)


def test_press_massSF_top_zero(press_result):
    result, *_ = press_result
    top = result["massSF"][0][-1, :]
    top = top.magnitude if hasattr(top, "magnitude") else np.array(top)
    np.testing.assert_allclose(top, 0.0, atol=1e-4)


def test_press_dt_sum_identity(press_result):
    """dt_sum = divm_z + divm_lat + adv_z + adv_lat  (sinksSources='0')."""
    result, *_ = press_result
    def v(k):
        x = result[k][0]
        return x.magnitude if hasattr(x, "magnitude") else np.array(x)
    expected = v("BA_divm_z") + v("BA_divm_lat") + v("BA_adv_z") + v("BA_adv_lat")
    dt = v("BA_dt_sum")
    mask = np.isfinite(dt) & np.isfinite(expected)
    np.testing.assert_allclose(dt[mask], expected[mask], rtol=1e-4)


def test_press_shape(press_result):
    result, lats, alts, binned = press_result
    vals = result["BA_chi_bar"][0]
    vals = vals.magnitude if hasattr(vals, "magnitude") else np.array(vals)
    assert vals.shape == (binned.sizes["alt"], len(lats))


def test_press_results_consistent_across_tracer_files(press_result):
    """Running with the second CLAMS press file must give the same output shape."""
    cfg = _press_config()
    req = ["PRESS", "THETA", "V", "OMEGA"]
    tracer2 = readAndTransposeData(str(CLAMS_PRESS_FILES[1]), ["BA"], "press", "lat", "lon")
    met     = _met_average(req)
    interp2 = interpolateToPressureAndCombineData(tracer2, met, req, cfg)
    binned2 = binData(interp2, 2, 1)
    res2, *_ = tracerTransportPress(binned2, cfg)
    result, *_ = press_result
    assert result["BA_chi_bar"][0].shape == res2["BA_chi_bar"][0].shape


# ===========================================================================
# TEM residual circulation
# ===========================================================================

def test_tem_output_vars_present(tem_result):
    for var in [
        "U", "V", "THETA", "W",
        "V_RES_STD", "W_RES_STD",
        "EPF_vert", "EPF_lat",
        "div_EPF_vert", "div_EPF_lat", "div_EPF",
        "MASS_SF_RES_STD",
    ]:
        assert var in tem_result, f"Missing TEM output variable: {var}"


def test_tem_output_shape(tem_result):
    assert tem_result.sizes["alt"] == len(_TARGET_LP)
    assert tem_result.sizes["lat"] == ERA5_SIZES["lat"]


def test_tem_v_res_std_finite(tem_result):
    assert np.sum(np.isfinite(tem_result["V_RES_STD"].values)) > 0


def test_tem_div_epf_finite(tem_result):
    assert np.sum(np.isfinite(tem_result["div_EPF"].values)) > 0


def test_tem_mass_sf_top_zero(tem_result):
    top = tem_result["MASS_SF_RES_STD"].values[-1, :]
    np.testing.assert_allclose(top, 0.0, atol=1e-3)


def test_tem_div_epf_equals_sum_of_components(tem_result):
    div_tot  = tem_result["div_EPF"].values
    div_vert = tem_result["div_EPF_vert"].values
    div_lat  = tem_result["div_EPF_lat"].values
    mask = np.isfinite(div_tot) & np.isfinite(div_vert) & np.isfinite(div_lat)
    np.testing.assert_allclose(div_tot[mask], (div_vert + div_lat)[mask], rtol=2e-4)


def test_tem_has_time_coordinate(tem_result):
    assert "time" in tem_result.coords


def test_tem_consistent_across_era5_files():
    """TEM output shape must be the same regardless of which ERA5 snapshot is used."""
    import pandas as pd
    cfg = _tem_config()
    req = ["PRESS", "THETA", "U", "V", "OMEGA"]
    shapes = []
    for f in ERA5_FILES:
        ds   = readAndTransposeData(str(f), req, "hybrid", "lat", "lon")
        ds_lp = interpolateToLogPressure(
            ds, req, "other", cfg["targetLevels"], "hybrid", "lat", "lon", "PRESS"
        )
        out = TEMCalcs(cfg, ds_lp, pd.Timestamp("2000-01-01T00"))
        shapes.append(out["V_RES_STD"].shape)
    assert len(set(shapes)) == 1, "TEM output shape varies across ERA5 files"
